### ISSUE TITLE
InvalidRange: The requested range is not satisfiable when `disabledChunk: true`

### ISSUE THREAD

**Issue by vecerek** [Borewit/tokenizer-s3#1201]
Sometimes I'm getting the following error:

```
InvalidRange: The requested range is not satisfiable
    at throwDefaultError (/app/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at /app/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39
    at de_GetObjectCommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4330:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
    at async /app/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46
    at async /app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
    at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
    at async makeTokenizer (/app/node_modules/@tokenizer/s3/lib/index.js:18:22)
    at async fp_ts_1.taskEither.tryCatch._typename (/app/packages/asset-repos/dist/asset/util/file-type.js:21:25)
```

`at async makeTokenizer (/app/node_modules/@tokenizer/s3/lib/index.js:18:22)` points to [this line](https://github.com/Borewit/tokenizer-s3/blob/e3ad15d14f7d55f6a115e02273e6097777fa43d3/lib/index.ts#L24). I'm not able to reproduce the error with a specific file. Once I can, I will update the issue.

Versions used:

| library | version |
| ------ | -------- |
| `@tokenizer/s3` | 0.2.3 |
| `@smithy/smithy-client` | 2.0.5 |

**Comment by johnf** [comment]
I get this with `disabledChunked: false` in the case where the file in S3 is empty.

I think the issue is at https://github.com/Borewit/tokenizer-s3/blob/master/lib/s3-request.ts#L48-L56
S3 throws an error due to the invalid range.

@Borewit I'm happy to do a PR if I could get some guidance. I'm not sure what makes the best sense.
I was thinking of returning `{}` on the catch, which would then be caught by https://github.com/Borewit/tokenizer-range/blob/master/lib/range-request-factory.ts#L56-L58 and at least throw a more meaningful error?

**Comment by Borewit** [comment]
Hi @johnf , thanks for looking into this. The best error messages usually generated at the place they occur. Caught exceptions can possibly at a bit of more complicated context information but should certainly not replace the original error message.

What would do you think be a more meaningful error?

I think the requested range and the file length would be interesting to add to the error, which could help to nail down this issue.

**Comment by vecerek** [comment]
Also, if you don't want to lose the original error, set the `cause` property on the wrapping error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause.

**Comment by vecerek** [comment]
FYI: I've just upgraded to the latest version and started getting the following errors (compared to 0 errors in the past 1 month):

```
EndOfStreamError: End-Of-Stream
    at ReadStreamTokenizer.readBuffer (file:///app/node_modules/strtok3/lib/ReadStreamTokenizer.js:37:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async ReadStreamTokenizer.ignore (file:///app/node_modules/strtok3/lib/ReadStreamTokenizer.js:85:31)
    at async _fromTokenizer (/app/node_modules/file-type/core.js:361:7)
```

I had to revert the change. Maybe I have to upgrade `file-type` as well in the same changeset. I'll try to investigate this a bit later.

**UPDATE**: it seems like the error was thrown from the [`_fromTokenizer` function](https://github.com/sindresorhus/file-type/blob/v16.5.4/core.js#L60). It does try to catch and ignore a `strtok3.EndOfStreamError`. My hypothesis is, that after I upgraded the library, the `EndOfStreamError` instance is no longer the same. I'll try to update both `file-type` and `@tokenizer/s3` at the same time and see how that goes.

**Comment by Borewit** [comment]
Hi @vecerek , if there is new/remaining issue, can you please raise that as a new issue, and help me to reproduce it? Looking forward to your feedback.
